export enum DocumentType {
  SIGNATURE = 'SIGNATURE',
  PAN_CARD = 'PAN_CARD',
  AADHAAR_FRONT = 'AADHAAR_FRONT',
  AADHAAR_BACK = 'AADHAAR_BACK',
  SHOP_FRONT = 'SHOP_FRONT',
  BUSINESS_PROOF = 'BUSINESS_PROOF',
  VIDEO_VERIFICATION = 'VIDEO_VERIFICATION',
}
