export const LOGGER_CONTEXT = {
  API_GATEWAY: 'API_GATEWAY',
  AUTH_SERVICE: 'AUTH_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  WALLET_SERVICE: 'WALLET_SERVICE',
  LEDGER_SERVICE: 'LEDGER_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
} as const;
