export const KAFKA_TOPICS = {
  USER_REGISTERED: 'auth.user.registered',
  USER_LOGGED_IN: 'auth.user.logged-in',
  USER_PASSWORD_CHANGED: 'auth.user.password-changed',
  SEND_EMAIL_OTP: 'otp.send.email',
  SEND_PHONE_OTP: 'otp.send.phone',
  EMAIL_SEND: 'notification.email.send',
  SMS_SEND: 'notification.sms.send',
  PUSH_SEND: 'notification.push.send',
  WALLET_CREATED: 'wallet.created',
  MONEY_ADDED: 'wallet.money.added',
  MONEY_TRANSFERRED: 'wallet.money.transferred',
  MONEY_ROLLBACK: 'wallet.money.rollback',
  TRANSACTION_CREATED: 'transaction.created',
  TRANSACTION_COMPLETED: 'transaction.completed',
  TRANSACTION_FAILD: 'transaction.failed',
  COMMISSION_CREATED: 'commission.created',
} as const;
