export const KAFKA_TOPICS = {
  USER_REGISTERED: 'auth.user.registered',
  USER_LOGGED_IN: 'auth.user.logged-in',
  USER_PASSWORD_CHANGED: 'auth.user.password-changed',
  USER_MPIN_CHANGED: 'auth.user.mpin-changed',
  USER_PASSWORD_RESET: 'auth.user.password-reset',
  USER_LOGIN_METHOD_CHANGED: 'auth.user.login-method-changed',
  AUTH_CREDENTIALS_ISSED: 'auth.credentials.issued',
  SEND_EMAIL_OTP: 'otp.send.email',
  SEND_PHONE_OTP: 'otp.send.phone',
  EMAIL_SEND: 'notification.email.send',
  SMS_SEND: 'notification.sms.send',
  PUSH_SEND: 'notification.push.send',
  KYC_SUBMITTED: 'kyc.submitted',
  KYC_APPROVED: 'kyc.approved',
  KYC_REJECTED: 'kyc.rejected',
  KYC_RESUBMISSION_REQUIRED: 'kyc.resuubmission-required',
  WALLET_CREATED: 'wallet.created',
  MONEY_ADDED: 'wallet.money.added',
  MONEY_TRANSFERRED: 'wallet.money.transferred',
  MONEY_ROLLBACK: 'wallet.money.rollback',
  TRANSACTION_CREATED: 'transaction.created',
  TRANSACTION_COMPLETED: 'transaction.completed',
  TRANSACTION_FAILD: 'transaction.failed',
  COMMISSION_CREATED: 'commission.created',
} as const;

