export const KYC_PATTERNS = {
  CREATE_KYC: 'kyc.create',
  GET_MY_KYC: 'kyc.get.me',
  GET_KYC: 'kyc.get',
  GET_DOCUMENTS: 'kyc.get-documents',
  UPLOAD_AADHAAR: 'kyc.upload-aadhar',
  UPDATE_AADHAAR: 'kyc.update-aadhaar',
  UPLOAD_DOCUMENT: 'kyc.upload-document',
  UPLOAD_VIDEO: 'kyc.upload-video',
  UPDATE_DOCUMENT: 'kyc.update-document',
  DELETE_DOCUMENT: 'kyc.delete-document',
  UPDATE_KYC: 'kyc.update',
  DELETE_KYC: 'kyc.delete',
  DELETE_VIDEO: 'kyc.delete-video',
  SUBMIT_KYC: 'kyc.submit',
} as const;
